export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_LIMIT_DATA = "GET_LIMIT_DATA";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";

export const GET_PRODUCTS_CATEGORY_FETCH = "GET_PRODUCTS_CATEGORY_FETCH";
export const GET_PRODUCTS_CATEGORY_SUCCESS = "GET_PRODUCTS_CATEGORY_SUCCESS";