export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_LIMIT_DATA = "GET_LIMIT_DATA";